baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'EZForm'
theme= 'hugo-whisper-theme'

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/getting-started"
    weight = 2